alias: Akkusteuerung
description: ""
triggers:
  - entity_id:
      - input_select.akkusteuerung_sma_wr
      - input_number.akkusteuerung_ladestaerke_soll
      - input_number.akkusteuerung_entladestaerke_soll
    from: null
    to: null
    for:
      hours: 0
      minutes: 0
      seconds: 1
    trigger: state
  - enabled: true
    trigger: time_pattern
    minutes: /5
  - event: start
    trigger: homeassistant
conditions: []
actions:
  - alias: Max Ladestärke (W)
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Max Ladeleistung (W)
      - condition: state
        entity_id: input_boolean.akku_automatik
        state: "on"
        enabled: false
    then:
      - alias: Betriebsart des BMS (Voreinstellung)
        data:
          hub: sma-sbs
          address: 40236
          slave: 3
          value:
            - 0
            - 2424
        action: modbus.write_register
      - alias: Minimale Batterieladeleistung (40793)
        data:
          hub: sma-sbs
          address: 40793
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
      - alias: Maximale Batterieladeleistung (40795)
        data:
          hub: sma-sbs
          address: 40795
          slave: 3
          value:
            - 0
            - >-
              {{ ( (states('input_number.akkusteuerung_ladestaerke_soll') |
              int)) }}
        action: modbus.write_register
      - alias: Minimale Batterieentladeleistung (40797)
        data:
          hub: sma-sbs
          address: 40797
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
      - alias: Maximale Batterieentladeleistung (40799)
        data:
          hub: sma-sbs
          address: 40799
          slave: 3
          value:
            - 0
            - >-
              {{ ( (states('input_number.akkusteuerung_entladestaerke_soll') |
              int)) }}
        action: modbus.write_register
      - data:
          hub: sma-sbs
          address: 40801
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Sollwert der Netzaustauschleistung (40801)
  - alias: Max Entladestärke (W)
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Max Entlade Leistung (W)
      - condition: state
        entity_id: input_boolean.akku_automatik
        state: "on"
        enabled: false
    then:
      - alias: Betriebsart des BMS (Voreinstellung)
        data:
          hub: sma-sbs
          address: 40236
          slave: 3
          value:
            - 0
            - 2290
        action: modbus.write_register
      - data:
          hub: sma-sbs
          address: 40793
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Minimale Batterieladeleistung (40793)
      - alias: Maximale Batterieladeleistung (40795)
        data:
          hub: sma-sbs
          address: 40795
          slave: 3
          value:
            - 0
            - >-
              {{ ( (states('input_number.akkusteuerung_ladestaerke_soll') |
              int)) }}
        action: modbus.write_register
      - alias: Minimale Batterieentladeleistung (40797)
        data:
          hub: sma-sbs
          address: 40797
          slave: 3
          value:
            - 0
            - >-
              {{ ( (states('input_number.akkusteuerung_entladestaerke_soll') |
              int)) }}
        action: modbus.write_register
      - alias: Maximale Batterieentladeleistung (40799)
        data:
          hub: sma-sbs
          address: 40799
          slave: 3
          value:
            - 0
            - >-
              {{ ( (states('input_number.akkusteuerung_entladestaerke_soll') |
              int)) }}
        action: modbus.write_register
      - data:
          hub: sma-sbs
          address: 40801
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Sollwert der Netzaustauschleistung (40801)
  - alias: Akku Pause (Standby)
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Akku Pause ( Standby)
      - condition: state
        entity_id: input_boolean.akku_automatik
        state: "on"
        enabled: false
    then:
      - data:
          hub: sma-sbs
          address: 40236
          slave: 3
          value:
            - 0
            - 2424
        action: modbus.write_register
        alias: Betriebsart des BMS (Voreinstellung)
      - data:
          hub: sma-sbs
          address: 40793
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Minimale Batterieladeleistung (40793)
      - alias: Maximale Batterieladeleistung (40795)
        data:
          hub: sma-sbs
          address: 40795
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
      - alias: Minimale Batterieentladeleistung (40797)
        data:
          hub: sma-sbs
          address: 40797
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
      - data:
          hub: sma-sbs
          address: 40799
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Maximale Batterieentladeleistung (40799)
      - data:
          hub: sma-sbs
          address: 40801
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Sollwert der Netzaustauschleistung (40801)
  - alias: Normal Modus
    if:
      - condition: state
        entity_id: input_select.akkusteuerung_sma_wr
        state: Normal Modus
      - condition: state
        entity_id: input_boolean.akku_automatik
        state: "on"
        enabled: false
    then:
      - data:
          hub: sma-sbs
          address: 40236
          slave: 3
          value:
            - 0
            - 2424
        action: modbus.write_register
        alias: Betriebsart des BMS (Voreinstellung)
      - data:
          hub: sma-sbs
          address: 40793
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Minimale Batterieladeleistung (40793)
      - alias: Maximale Batterieladeleistung (40795)
        data:
          hub: sma-sbs
          address: 40795
          slave: 3
          value:
            - 0
            - 4600
        action: modbus.write_register
      - alias: Minimale Batterieentladeleistung (40797)
        data:
          hub: sma-sbs
          address: 40797
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
      - alias: Maximale Batterieentladeleistung (40799)
        data:
          hub: sma-sbs
          address: 40799
          slave: 3
          value:
            - 0
            - 5000
        action: modbus.write_register
      - data:
          hub: sma-sbs
          address: 40801
          slave: 3
          value:
            - 0
            - 0
        action: modbus.write_register
        alias: Sollwert der Netzaustauschleistung (40801)
mode: single
