blueprint:
  name: Akkusteuerung (feste Register)
  description: >
    Steuerung des Lade-/Entlademodus via Modbus mit festen Registeradressen.
  domain: automation
  input:
    battery_control_select:
      name: Akkumodus Auswahl
      selector:
        entity:
          domain: input_select
    auto_mode_toggle:
      name: Akkubetrieb Automatik
      selector:
        entity:
          domain: input_boolean
    ladestaerke_soll:
      name: Batterieladeleistung Sollwert
      selector:
        entity:
          domain: input_number
    entladestaerke_soll:
      name: Batterieentladeleistung Sollwert
      selector:
        entity:
          domain: input_number

trigger:
  - platform: state
    entity_id:
      - !input battery_control_select
      - !input ladestaerke_soll
      - !input entladestaerke_soll
    for:
      seconds: 1
  - platform: time_pattern
    minutes: "/3"
  - platform: homeassistant
    event: start

condition: []

action:
  - alias: Modus Max Entladeleistung
    if:
      - condition: state
        entity_id: !input battery_control_select
        state: "Max Entlade Leistung (W)"
      - condition: state
        entity_id: !input auto_mode_toggle
        state: "on"
    then:
      - alias: BMS Betriebsart auf Schnell Entladen setzen
        service: modbus.write_register
        data:
          hub: sma-sbs
          address: 40236
          slave: 3
          value:
            - 0
            - 2290

      - alias: Minimale Ladeleistung (40793) auf 0
        service: modbus.write_register
        data:
          hub: sma-sbs
          address: 40793
          slave: 3
          value:
            - 0
            - 0

      - alias: Maximale Ladeleistung (40795) setzen
        service: modbus.write_register
        data:
          hub: sma-sbs
          address: 40795
          slave: 3
          value:
            - 0
            - "{{ states('input_number.akkusteuerung_ladestaerke_soll') | int }}"

      - alias: Minimale Entladeleistung (40797) setzen
        service: modbus.write_register
        data:
          hub: sma-sbs
          address: 40797
          slave: 3
          value:
            - 0
            - "{{ states('input_number.akkusteuerung_entladestaerke_soll') | int }}"

      - alias: Maximale Entladeleistung (40799) setzen
        service: modbus.write_register
        data:
          hub: sma-sbs
          address: 40799
          slave: 3
          value:
            - 0
            - "{{ states('input_number.akkusteuerung_entladestaerke_soll') | int }}"

      - alias: Netzaustauschleistung (40801) auf 0 setzen
        service: modbus.write_register
        data:
          hub: sma-sbs
          address: 40801
          slave: 3
          value:
            - 0
            - 0

mode: single
