blueprint:
  name: Akkusteuerung via Modbus (konfigurierbar)
  description: >
    Dieser Blueprint steuert über Modbus verschiedene Lade- und Entladeprofile
    der Batterie. Alle wichtigen Parameter (Input‑Entities, Modbus-Hub, Slave, Registeradressen und
    Sollwerte) können individuell angepasst werden.
  domain: automation
  input:
    battery_control_select:
      name: Akkusteuerung Auswahl
      description: "Wähle den Akkusteuerungsmodus (z. B. 'Akku schnell Laden', 'Akku schnell Entladen', 'Akku Pause', 'Akku 0.2C laden' oder 'Normal Modus')."
      selector:
        entity:
          domain: input_select
    auto_mode_toggle:
      name: Akkubetrieb Automatik
      description: "Schalter, ob die automatisierte Akkusteuerung aktiv ist."
      selector:
        entity:
          domain: input_boolean
    ladestaerke_soll:
      name: Batterieladeleistung Sollwert
      description: "Sollwert für die maximale Batterieladeleistung (Modus 'Akku schnell Laden')."
      selector:
        entity:
          domain: input_number
    entladestaerke_soll:
      name: Batterieentladeleistung Sollwert
      description: "Sollwert für die maximale Batterieentladeleistung (Modus 'Akku schnell Entladen')."
      selector:
        entity:
          domain: input_number
    ladestaerke_02c:
      name: 0.2C Ladeleistung
      description: "Sollwert für die maximale Batterieladeleistung (Modus 'Akku 0.2C laden')."
      selector:
        entity:
          domain: input_number

    modbus_hub:
      name: Modbus Hub
      description: "Name des Modbus Hubs (z. B. sma-sr_wr)."
      default: sma-sr_wr
      selector:
        text: {}

    modbus_slave:
      name: Modbus Slave
      description: "Slave Nummer im Modbus-Netz (z. B. 3)."
      default: 3
      selector:
        number:
          min: 1
          max: 10

    register_bms_mode:
      name: Register BMS Betriebsart
      description: "Registeradresse für die Betriebsart (BMS)."
      default: 40236
      selector:
        number:
          min: 0
          max: 65535
    register_min_lade:
      name: Register Minimale Batterieladeleistung
      default: 40793
      selector:
        number:
          min: 0
          max: 65535
    register_max_lade:
      name: Register Maximale Batterieladeleistung
      default: 40795
      selector:
        number:
          min: 0
          max: 65535
    register_min_entlade:
      name: Register Minimale Batterieentladeleistung
      default: 40797
      selector:
        number:
          min: 0
          max: 65535
    register_max_entlade:
      name: Register Maximale Batterieentladeleistung
      default: 40799
      selector:
        number:
          min: 0
          max: 65535
    register_netzaustausch:
      name: Register Sollwert Netzaustauschleistung
      default: 40801
      selector:
        number:
          min: 0
          max: 65535

    value_bms_mode_normal:
      name: Wert BMS Betriebsart Normal
      description: "Wert für die Betriebsart (Normal/Voreinstellung) bei Laden oder Pause."
      default: 2424
      selector:
        number:
          min: 0
          max: 10000
    value_bms_mode_schnell_entladen:
      name: Wert BMS Betriebsart Schnell Entladen
      description: "Wert für die Betriebsart (schnell Entladen)."
      default: 2290
      selector:
        number:
          min: 0
          max: 10000
    value_max_entlade_normal:
      name: Wert Maximale Batterieentladeleistung Normal
      description: "Wert für maximale Batterieentladeleistung im Normal Modus."
      default: 5000
      selector:
        number:
          min: 0
          max: 10000
    value_max_entlade_schnell:
      name: Wert Maximale Batterieentladeleistung Schnell
      description: "Wert für maximale Batterieentladeleistung im Schnell-Entlade Modus."
      default: 4600
      selector:
        number:
          min: 0
          max: 10000
    value_max_lade_schnell:
      name: Wert Maximale Batterieladeleistung Schnell
      description: "Wert für maximale Batterieladeleistung im Schnell-Lade Modus."
      default: 4600
      selector:
        number:
          min: 0
          max: 10000

trigger:
  - platform: state
    entity_id:
      - !input battery_control_select
      - !input ladestaerke_soll
      - !input entladestaerke_soll
      - !input ladestaerke_02c
    for:
      seconds: 1
  - platform: time_pattern
    minutes: '/5'
  - platform: event
    event_type: start

condition: []
action:
  - choose:
      # Hier folgen die choose-Blöcke für die unterschiedlichen Akkumodi...
      # (siehe vorheriges Beispiel)
mode: single
