blueprint:
  name: Akkusteuerung via Modbus (konfigurierbar)
  description: >
    Dieser Blueprint steuert über Modbus verschiedene Lade- und Entladeprofile
    der Batterie. Alle wichtigen Parameter (Input‑Entities, Modbus-Hub, Slave, Registeradressen und
    Sollwerte) können individuell angepasst werden.
  domain: automation
  input:
    battery_control_select:
      name: Akkusteuerung Auswahl
      selector:
        entity:
          domain: input_select
    auto_mode_toggle:
      name: Akkubetrieb Automatik
      selector:
        entity:
          domain: input_boolean
    ladestaerke_soll:
      name: Batterieladeleistung Sollwert
      selector:
        entity:
          domain: input_number
    entladestaerke_soll:
      name: Batterieentladeleistung Sollwert
      selector:
        entity:
          domain: input_number
    ladestaerke_02c:
      name: 0.2C Ladeleistung
      selector:
        entity:
          domain: input_number

    modbus_hub:
      name: Modbus Hub
      default: sma-sr_wr
      selector:
        text: {}
    modbus_slave:
      name: Modbus Slave
      default: 3
      selector:
        number:
          min: 1
          max: 10
    register_bms_mode:
      name: Register BMS Betriebsart
      default: 40236
      selector:
        number:
          min: 0
          max: 65535
    register_min_lade:
      name: Register Minimale Batterieladeleistung
      default: 40793
      selector:
        number:
          min: 0
          max: 65535
    register_max_lade:
      name: Register Maximale Batterieladeleistung
      default: 40795
      selector:
        number:
          min: 0
          max: 65535
    register_min_entlade:
      name: Register Minimale Batterieentladeleistung
      default: 40797
      selector:
        number:
          min: 0
          max: 65535
    register_max_entlade:
      name: Register Maximale Batterieentladeleistung
      default: 40799
      selector:
        number:
          min: 0
          max: 65535
    register_netzaustausch:
      name: Register Sollwert Netzaustauschleistung
      default: 40801
      selector:
        number:
          min: 0
          max: 65535

    value_bms_mode_normal:
      name: Wert BMS Betriebsart Normal
      default: 2424
      selector:
        number:
          min: 0
          max: 10000
    value_bms_mode_schnell_entladen:
      name: Wert BMS Betriebsart Schnell Entladen
      default: 2290
      selector:
        number:
          min: 0
          max: 10000
    value_max_entlade_normal:
      name: Wert Maximale Batterieentladeleistung Normal
      default: 5000
      selector:
        number:
          min: 0
          max: 10000
    value_max_entlade_schnell:
      name: Wert Maximale Batterieentladeleistung Schnell
      default: 4600
      selector:
        number:
          min: 0
          max: 10000
    value_max_lade_schnell:
      name: Wert Maximale Batterieladeleistung Schnell
      default: 4600
      selector:
        number:
          min: 0
          max: 10000

trigger:
  - platform: state
    entity_id: !input battery_control_select
    for:
      seconds: 1
  - platform: time_pattern
    minutes: "/5"
  - platform: homeassistant
    event: start

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "false"
        sequence:
          - service: system_log.write
            data:
              message: "Dies ist ein Dummy-Eintrag, um das Speichern zu ermöglichen."
              level: warning
mode: single
