blueprint:
  name: Akkusteuerung via Modbus (konfigurierbar, feste Register)
  description: >
    Dieser Blueprint steuert über Modbus verschiedene Lade- und Entladeprofile
    der Batterie. Registeradressen sind fest definiert.
  domain: automation
  input:
    battery_control_select:
      name: Akkusteuerung Auswahl
      selector:
        entity:
          domain: input_select
    auto_mode_toggle:
      name: Akkubetrieb Automatik
      selector:
        entity:
          domain: input_boolean
    ladestaerke_soll:
      name: Batterieladeleistung Sollwert
      selector:
        entity:
          domain: input_number
    entladestaerke_soll:
      name: Batterieentladeleistung Sollwert
      selector:
        entity:
          domain: input_number
    ladestaerke_02c:
      name: 0.2C Ladeleistung
      selector:
        entity:
          domain: input_number
    modbus_hub:
      name: Modbus Hub
      default: sma-sr_wr
      selector:
        text: {}
    modbus_slave:
      name: Modbus Slave
      default: 3
      selector:
        number:
          min: 1
          max: 10

    value_bms_mode_normal:
      name: Wert BMS Betriebsart Normal
      default: 2424
      selector:
        number:
          min: 0
          max: 10000
    value_bms_mode_schnell_entladen:
      name: Wert BMS Betriebsart Schnell Entladen
      default: 2290
      selector:
        number:
          min: 0
          max: 10000
    value_max_entlade_normal:
      name: Wert Maximale Batterieentladeleistung Normal
      default: 5000
      selector:
        number:
          min: 0
          max: 10000
    value_max_entlade_schnell:
      name: Wert Maximale Batterieentladeleistung Schnell
      default: 4600
      selector:
        number:
          min: 0
          max: 10000
    value_max_lade_schnell:
      name: Wert Maximale Batterieladeleistung Schnell
      default: 4600
      selector:
        number:
          min: 0
          max: 10000

trigger:
  - platform: state
    entity_id: !input battery_control_select
    for:
      seconds: 1
  - platform: time_pattern
    minutes: "/5"
  - platform: homeassistant
    event: start

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input battery_control_select
            state: "Akku schnell Entladen"
          - condition: state
            entity_id: !input auto_mode_toggle
            state: "on"
        sequence:
          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              slave: !input modbus_slave
              address: 40236
              value: !input value_bms_mode_schnell_entladen

          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              slave: !input modbus_slave
              address: 40793
              value: 0

          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              slave: !input modbus_slave
              address: 40795
              value: 0

          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              slave: !input modbus_slave
              address: 40797
              value: 0

          - service: modbus.write_register
            data:
              hub: !input modbus_hub
              slave: !input modbus_slave
              address: 40799
              value: !input value_max_entlade_schnell

mode: single
